spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/servidor_database
spring.datasource.username=jose
spring.datasource.password=2002
# Antes: cada reinicio borra todo
# spring.jpa.hibernate.ddl-auto=create-drop

# Ahora: solo crea tablas si no existen, no borra datos
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Indicar schema por defecto
spring.jpa.properties.hibernate.default_schema=public

# limitar conexciones maximas del servidor
server.tomcat.max-connections=1500

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat
server.port=8443
