spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/servidor_database
spring.datasource.username=jose
spring.datasource.password=2002
# Antes: cada reinicio borra todo
# spring.jpa.hibernate.ddl-auto=create-drop

# Ahora: solo crea tablas si no existen, no borra datos
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Indicar schema por defecto
spring.jpa.properties.hibernate.default_schema=public

# extra logging for hibernate, luego borrar
# logging.level.root=ERROR
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE