# Nombre de la aplicación
spring.application.name=demo
# URL de la base de datos (host, puerto y nombre)
spring.datasource.url=jdbc:postgresql://localhost:5432/servidor_database
# Usuario de la base de datos
spring.datasource.username=jose
# Contraseña de la base de datos
spring.datasource.password=2002

# Hibernate, A FUTURO VALIDATE
# Actualiza automáticamente las tablas según las entidades
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en consola
spring.jpa.show-sql=true
# Formatea el SQL para que sea más legible
spring.jpa.properties.hibernate.format_sql=true
# Dialecto específico para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Esquema por defecto de la base de datos
spring.jpa.properties.hibernate.default_schema=public

# Limitar conexiones
# Número máximo de conexiones simultáneas al servidor
server.tomcat.max-connections=1500

# SSL (Reactivado para coincidir con el frontend)
# HTTPS seguro
# Ruta del archivo de certificado dentro del proyecto (resources)
server.ssl.key-store=classpath:keystore.p12
# Contraseña para acceder al certificado
server.ssl.key-store-password=123456
# Tipo de archivo del certificado
server.ssl.keyStoreType=PKCS12
# Alias interno del certificado dentro del keystore
server.ssl.keyAlias=tomcat
# Puerto HTTPS (acceso seguro)
server.port=8443

# --- CONFIGURACIÓN DE CORREO (Gmail) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=LinkedListOficial@gmail.com
spring.mail.password=wzxozwqxdnrmohaf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true